name: consumers-voice-system
type: web
runtime: dotnet
buildCommand: dotnet publish ConsumersVoiceSystemPrototype.csproj -c Release -o publish
startCommand: dotnet publish/ConsumersVoiceSystemPrototype.dll
envVars:
  - key: USE_SQLITE
    value: "1"
  - key: ASPNETCORE_ENVIRONMENT
    value: Production